repositories:
- name: elastic-stack
  url: https://helm.elastic.co

environments:
  dev-gcp:
  prod:

releases:
- name: kibana
  namespace: gitlab-managed-apps
  chart: elastic/kibana
  version: 8.5.1
  installed: true
  values:
    - values.yaml.gotmpl
